add github

diff --git a/.github/workflows/sync_to_ncp.yml b/.github/workflows/sync_to_ncp.yml
--- a/.github/workflows/sync_to_ncp.yml
+++ b/.github/workflows/sync_to_ncp.yml
@@ -34,4 +34,5 @@ jobs:
       - name: Mirror push to NCP SourceCommit
         run: |
           echo "Pushing all branches and tags to NCP..."
-          git push --mirror origin || (echo "Push failed. Exiting..." && exit 1)
+          git push origin --all || (echo "Push failed. Exiting..." && exit 1)
+          git push origin --tags || (echo "Push failed. Exiting..." && exit 1)
